{
 "title": "gNMIc",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Target Subscription Uptimes",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gnmic_target_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Ingress to Jetstream send duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_jetstream_output_msg_send_duration_ns",
     "legendFormat": "{{publisher_id}}"
    }
   ]
  },
  {
   "title": "Egress write duration to Prometheus",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_prometheus_write_output_msg_send_duration_ns",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ingress to jetstream failures",
   "type": "timeseries",
   "description": "failures to write from ingress to jetstream per 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "- rate(gnmic_jetstream_output_number_of_jetstream_msgs_sent_fail_total{}[2m])",
     "legendFormat": "Fails: {{publisher_id}}/{{ subject }}"
    }
   ]
  },
  {
   "title": "Ingress to jetstream successes",
   "type": "timeseries",
   "description": "completed writes from ingress to jetstream per 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(gnmic_jetstream_output_number_of_jetstream_msgs_sent_success_total{}[2m])",
     "legendFormat": "{{ publisher_id }}/{{ subject }}"
    }
   ]
  }
 ]
}