# Optional overlay: add Cisco IOS-XE (C9k) ingestor and use combined emitter (srl + eos + iosxe).
# Usage:
#   docker compose -f compose.yaml -f compose-iosxe.yaml up -d
# Ensure gnmic/gnmic-ingestor-iosxe.yaml has your CML C9k targets and credentials.
networks:
  gnp-mgmt:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.60.0/24

services:
  gnmic-ingestor-iosxe:
    image: ghcr.io/openconfig/gnmic:0.42.0
    ports:
      - 9805:7890
    volumes:
      - ./gnmic/gnmic-ingestor-iosxe.yaml:/app/gnmic.yaml:ro
    command: ["--config", "/app/gnmic.yaml", "--log", "subscribe"]
    networks:
      - gnp-mgmt

  gnmic-emitter:
    volumes:
      - ./gnmic/gnmic-emitter-iosxe.yaml:/app/gnmic.yaml:ro
    # Same command; config now includes iosxe JetStream input.
